version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      # - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips64
      - mips64le
      - ppc64
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    binary: tailout

archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

changelog:
  disable: true
