version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - solaris
      - windows
    flags:
      - -trimpath
    binary: tailout

archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

changelog:
  disable: true
